# Generated by Django 4.2.4 on 2023-08-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction_listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('brief_description', models.CharField(max_length=200)),
                ('seller_name', models.CharField(max_length=50)),
            ],
        ),
    ]
