# Generated by Django 4.2.4 on 2023-08-22 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_listing'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auction_listing',
            new_name='AuctionListing',
        ),
    ]
