# Generated by Django 4.2.4 on 2023-08-22 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_auction_listing_auctionlisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='seller_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellername', to=settings.AUTH_USER_MODEL),
        ),
    ]
