# Generated by Django 4.2.4 on 2023-08-29 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='brief_description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
