# Generated by Django 4.2.4 on 2023-08-29 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_auctionlisting_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='brief_description',
            field=models.CharField(blank=True, default=0.0, max_length=200),
        ),
    ]
